wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.27.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1779203265
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      2:
      - 2
      - 3
      - 5
      - 53
      3:
      - 2
      - 4
      - 13
      - 16
      - 42
      - 62
      4: 3.12.7
      5: 0.27.0
      8:
      - 1
      - 3
      10:
      - 20
      13: windows-amd64
    e:
      fc0w32dllsj284jbh3tvnagqexlqcj80:
        os: Windows-11-10.0.26200-SP0
        python: CPython 3.12.7
        started_at: '2026-05-19T15:07:45.628320Z'
        program: d:\atri-fashion-mnist-assignment\notebooks\Q4_wandb_sweep.ipynb
        code_path: d:\atri-fashion-mnist-assignment\notebooks\Q4_wandb_sweep.ipynb
        code_path_local: Q4_wandb_sweep.ipynb
        root: d:\atri-fashion-mnist-assignment\notebooks
        host: DESKTOP-VQO8P1H
        executable: c:\Users\harik\anaconda3\anoconda\python.exe
        cpu_count: 4
        cpu_count_logical: 8
        disk:
          /:
            total: '140504985600'
            used: '38947934208'
        memory:
          total: '8311836672'
        writer_id: fc0w32dllsj284jbh3tvnagqexlqcj80
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
num_hidden_layers:
  desc: null
  value: 4
hidden_layer_size:
  desc: null
  value: 64
weight_decay:
  desc: null
  value: 0.5
optimizer:
  desc: null
  value: rmsprop
weight_init:
  desc: null
  value: xavier
activation:
  desc: null
  value: relu
